server:
  port: 8181 
  servlet.context-path: /li.nicetry.app.service
  
logging:
  pattern:
    console: "%msg%n"
  level:
    root: ERROR
    org.springframework.web: INFO
    li.nicetry: DEBUG

spring:
  jackson:
    default-property-inclusion: NON_NULL
    
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env
 
urlToPdfService:
  url: https://url-to-pdf-api.herokuapp.com/api
  endpoint: /render