server:
  port: 8181 
  servlet.context-path: /nicetry
  
logging:
  pattern:
    console: "%msg%n"
  level:
    root: ERROR
    org.springframework.web: INFO
    li.nicetry: DEBUG

spring:
  profiles:
    active: local
  jackson:
    default-property-inclusion: NON_NULL
    
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env
 
pdfConverterService:
  url: https://url-to-pdf-api.herokuapp.com/api/render 
 